In [1]:
import pandas as pd
from pandas import DataFrame
import numpy as np
# import matplotlib.pyplot as plt
# import scipy.stats as stats
# import plotly.express as px
# import plotly.graph_objects as go
# import plotly.subplots as sp
# from typing import List

from datasets import load_d4ls

pd.set_option('display.max_columns', None)

In [2]:
train_anndata = load_d4ls.load_full_anndata()

In [3]:
train_anndata.obs.Position.sum()/len(train_anndata.obs)#[['image', 'sample_id']]

1.1584224062569946

In [7]:
train_anndata.obs.columns

Index(['image', 'sample_id', 'ObjectNumber', 'Pos_X', 'Pos_Y', 'area',
       'major_axis_length', 'minor_axis_length', 'eccentricity', 'width_px',
       'height_px', 'acquisition_id', 'SlideId', 'Study', 'Box.Description',
       'Position', 'SampleId', 'Indication', 'BatchId', 'SubBatchId', 'ROI',
       'ROIonSlide', 'includeImage', 'flag_no_cells', 'flag_no_ROI',
       'flag_total_area', 'flag_percent_covered', 'small_cell', 'celltypes',
       'flag_tumor', 'PD1_pos', 'Ki67_pos', 'cleavedPARP_pos', 'GrzB_pos',
       'tumor_patches', 'distToCells', 'CD20_patches', 'Batch', 'cell_labels'],
      dtype='object')

In [18]:
len(train_anndata.obs)

236791

In [16]:
train_anndata.obs[['image', 'Indication']].groupby('Indication').count()

C:\Users\przem\AppData\Local\Temp\ipykernel_12512\1889055616.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  train_anndata.obs[['image', 'Indication']].groupby('Indication').count()


image
Indication       
BREAS       56225
GI          39413
GU          41485
HN          45062
THOR        54606

In [17]:
train_anndata.obs[['image', 'Study']].groupby('Study').count()

C:\Users\przem\AppData\Local\Temp\ipykernel_12512\1596316263.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  train_anndata.obs[['image', 'Study']].groupby('Study').count()


image
Study               
170245_E1559   30017
170250_LUNG    31115
180305_THOR    14553
180311_GI      13916
180327_HN       4884
180345_BREAS    8087
190346_GU      18329
190370_SPECT  115890

In [10]:
train_anndata.obs.Indication

IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_1     THOR
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_3     THOR
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_5     THOR
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_7     THOR
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_8     THOR
                                                                    ...  
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713                  BREAS
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715                  BREAS
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721                  BREAS
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722                  BREAS
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725                  BREAS
Name: Indication, Length: 236791, dtype: category
Categories (5, object): ['BREAS', 'GI', 'GU', 'HN', 'THOR']

In [9]:
train_anndata.obs.Study

IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_1     180305_THOR
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_3     180305_THOR
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_5     180305_THOR
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_7     180305_THOR
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_8     180305_THOR
                                                                        ...     
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2713                  190370_SPECT
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2715                  190370_SPECT
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2721                  190370_SPECT
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2722                  190370_SPECT
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725                  190370_SPECT
Name: Study, Length: 236791, dtype: category
Categories (8, object): ['170245_E1559', '170250_LUNG', '180305_

In [6]:
train_anndata.var

channel  use_channel             marker
0      Y89            1                MPO
1    In113            0          HistoneH3
2    In115            1                SMA
3    Pr141            1               CD16
4    Nd142            1               CD38
5    Nd143            1              HLADR
6    Nd144            1               CD27
7    Nd145            1               CD15
8    Nd146            1             CD45RA
9    Sm147            1              CD163
10   Nd148            1                B2M
11   Sm149            1               CD20
12   Nd150            1               CD68
13   Eu151            1               Ido1
14   Sm152            1                CD3
15   Eu153            1               LAG3
16   Sm154            1              CD11c
17   Gd155            1                PD1
18   Gd156            1             PDGFRb
19   Gd158            1                CD7
20   Tb159            1               GrzB
21   Gd160            1               PDL1
22   Dy161            1               TCF7
23   Dy162            1             CD45RO
24   Dy163            1              FOXP3
25   Dy164            1               ICOS
26   Ho165            1               CD8a
27   Er166            1  CarbonicAnhydrase
28   Er167            1               CD33
29   Er168            1               Ki67
30   Tm169            1              VISTA
31   Er170            1               CD40
32   Yb171            1                CD4
33   Yb172            1               CD14
34   Yb173            1               Ecad
35   Yb174            1              CD303
36   Lu175            1              CD206
37   Yb176            1        cleavedPARP
38   Ir191            0               DNA1
39   Ir193            0               DNA2

In [10]:
train_anndata.obs.columns

Index(['image', 'sample_id', 'ObjectNumber', 'Pos_X', 'Pos_Y', 'area',
       'major_axis_length', 'minor_axis_length', 'eccentricity', 'width_px',
       'height_px', 'acquisition_id', 'SlideId', 'Study', 'Box.Description',
       'Position', 'SampleId', 'Indication', 'BatchId', 'SubBatchId', 'ROI',
       'ROIonSlide', 'includeImage', 'flag_no_cells', 'flag_no_ROI',
       'flag_total_area', 'flag_percent_covered', 'small_cell', 'celltypes',
       'flag_tumor', 'PD1_pos', 'Ki67_pos', 'cleavedPARP_pos', 'GrzB_pos',
       'tumor_patches', 'distToCells', 'CD20_patches', 'Batch', 'cell_labels'],
      dtype='object')

In [25]:
(train_anndata.obs.Position == 0).any()


False

In [28]:
train_anndata.obs[['ROI']].value_counts()

ROI
1      71707
2      69438
3      69337
4      26309
Name: count, dtype: int64

In [35]:
train_anndata.obs[['Indication']].value_counts()

Indication
BREAS         56225
THOR          54606
HN            45062
GU            41485
GI            39413
Name: count, dtype: int64

In [41]:
df = train_anndata.obs

In [47]:
df.image[0], df.index[0]

C:\Users\przem\AppData\Local\Temp\ipykernel_2212\2034776871.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.image[0], df.index[0]


('IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff',
 'IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_1')

In [45]:
df.image.value_counts()

image
IMMUcan_Batch20210921_LUNG_10041543-LUNG-VAR-TIS-01-IMC-01_003.tiff    5152
IMMUcan_Batch20210921_UPSTREAM_S-210622-00014_004.tiff                 3746
IMMUcan_Batch20210701_UPSTREAM_S-210510-00068_001.tiff                 3488
IMMUcan_Batch20210304_10070084-SPECT-VAR-TIS-01-IMC-01_002.tiff        3439
IMMUcan_Batch20210701_S-210531-00020_001.tiff                          3342
                                                                       ... 
IMMUcan_Batch20201113_10052392-BREAS-VAR-TIS-UNST-03_001.tiff           655
IMMUcan_2022_WFLOW_10072131-SPECT-VAR-TIS-01-IMC-01_001.tiff            563
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff          487
IMMUcan_Batch20220609_10089094-SPECT-VAR-TIS-01-IMC-01_001.tiff         352
IMMUcan_Batch20210506_10068594-SPECT-VAR-TIS-01-IMC-01_003.tiff         340
Name: count, Length: 125, dtype: int64

In [44]:
df.index.value_counts()

IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_1                 1
IMMUcan_SPECTA_LUNG_S-210531-00014_001.tiff_1895                                 1
IMMUcan_SPECTA_LUNG_S-210531-00014_001.tiff_1898                                 1
IMMUcan_SPECTA_LUNG_S-210531-00014_001.tiff_1899                                 1
IMMUcan_SPECTA_LUNG_S-210531-00014_001.tiff_1900                                 1
                                                                                ..
IMMUcan_Batch20210506_UPSTREAM_10064754-E1559-VAR-TIS-01-IMC-01_001.tiff_1049    1
IMMUcan_Batch20210506_UPSTREAM_10064754-E1559-VAR-TIS-01-IMC-01_001.tiff_1050    1
IMMUcan_Batch20210506_UPSTREAM_10064754-E1559-VAR-TIS-01-IMC-01_001.tiff_1051    1
IMMUcan_Batch20210506_UPSTREAM_10064754-E1559-VAR-TIS-01-IMC-01_001.tiff_1052    1
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725                               1
Name: count, Length: 236791, dtype: int64

In [48]:
len(df.set_index('image'))

236791

In [52]:
df.head()

image  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   

                                                                                            sample_id  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   

                                                    ObjectNumber       Pos_X  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           1.0  300.846154   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           3.0   26.982143   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           5.0  309.083333   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           7.0  431.916667   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           8.0  116.931034   

                                                       Pos_Y  area  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  0.692308  13.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  0.928571  56.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  0.750000  12.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  0.750000  12.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  1.206897  29.0   

                                                    major_axis_length  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           6.094800   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...          21.520654   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           5.294329   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           5.294329   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           9.216670   

                                                    minor_axis_length  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           2.780135   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           3.368407   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           2.862220   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           2.862220   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           4.112503   

                                                    eccentricity  width_px  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      0.889904     600.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      0.987675     600.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      0.841267     600.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      0.841267     600.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      0.894932     600.0   

                                                    height_px  acquisition_id  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      600.0             2.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      600.0             2.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      600.0             2.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      600.0             2.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...      600.0             2.0   

                                                                            SlideId  \
IMMUcan_bat

In [57]:
df[['Pos_X', 'Pos_Y', ]].values

array([[300.84615385,   0.69230769],
       [ 26.98214286,   0.92857143],
       [309.08333333,   0.75      ],
       ...,
       [ 48.37037037, 598.11111111],
       [207.96969697, 598.06060606],
       [565.9375    , 597.6875    ]])

In [58]:
df['image'].unique()

['IMMUcan_batch20191023_10032145-THOR-VAR-TIS-0..., 'IMMUcan_Batch20191023_10032401-HN-VAR-TIS-01-..., 'IMMUcan_Batch20191023_S-190701-00035_006.tiff', 'IMMUcan_Batch20191023_S-190805-00002_006.tiff', 'IMMUcan_Batch20200528_10032890-THOR-VAR-TIS-0..., ..., 'IMMUcan_Batch20220609_S-220506-00008_002.tiff', 'IMMUcan_Batch20220908_S-220513-00020_001.tiff', 'IMMUcan_Batch20220908_S-220513-00020_003.tiff', 'IMMUcan_Batch20220908_S-220715-00002_002.tiff', 'IMMUcan_Batch20220908_S-220729-00002_002.tiff']
Length: 125
Categories (125, object): ['10068190-SPECT-VAR-TIS-01-IMC-01_001.tiff', 'IMMUcan_2022_WFLOW_10034294-GI-VAR-TIS-UNST-0..., 'IMMUcan_2022_WFLOW_10061074-SPECT-VAR-TIS-01-..., 'IMMUcan_2022_WFLOW_10063152-SPECT-VAR-TIS-01-..., ..., 'IMMUcan_SPECTA_LUNG_S-210607-00002_001.tiff', 'IMMUcan_WFLOW_Batch20210304_10043243-GI-VAR-T..., 'IMMUcan_WFLOW_Batch20210304_10067564-SPECT-VA..., 'IMMUcan_batch20191023_10032145-THOR-VAR-TIS-0...]

In [55]:
df[['image', 'sample_id', 'area', 'eccentricity', 'cell_labels']].head()

image  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   

                                                                                            sample_id  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   

                                                         Pos_X     Pos_Y  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  300.846154  0.692308   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...   26.982143  0.928571   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  309.083333  0.750000   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  431.916667  0.750000   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  116.931034  1.206897   

                                                    area  eccentricity  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  13.0      0.889904   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  56.0      0.987675   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  12.0      0.841267   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  12.0      0.841267   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  29.0      0.894932   

                                                   cell_labels  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    MacCD163  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Mural  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...          DC  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Tumor  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Tumor

In [59]:
df[df['image'] == df['image'].unique()[0]][['sample_id', 'area', 'eccentricity', 'cell_labels']]

sample_id  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
...                                                                                               ...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   

                                                    area  eccentricity  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  13.0      0.889904   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  56.0      0.987675   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  12.0      0.841267   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  12.0      0.841267   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  29.0      0.894932   
...                                                  ...           ...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  71.0      0.852971   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  78.0      0.908007   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  44.0      0.835862   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  47.0      0.771517   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  27.0      0.868378   

                                                   cell_labels  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    MacCD163  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Mural  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...          DC  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Tumor  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Tumor  
...                                                        ...  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Mural  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Mural  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...          NK  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...        Treg  
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...       Mural  

[487 rows x 4 columns]

In [63]:
df.sample_id.value_counts()

sample_id
IMMUcan_Batch20210921_LUNG_10041543-LUNG-VAR-TIS-01-IMC-01_003    5152
IMMUcan_Batch20210921_UPSTREAM_S-210622-00014_004                 3746
IMMUcan_Batch20210701_UPSTREAM_S-210510-00068_001                 3488
IMMUcan_Batch20210304_10070084-SPECT-VAR-TIS-01-IMC-01_002        3439
IMMUcan_Batch20210701_S-210531-00020_001                          3342
                                                                  ... 
IMMUcan_Batch20201113_10052392-BREAS-VAR-TIS-UNST-03_001           655
IMMUcan_2022_WFLOW_10072131-SPECT-VAR-TIS-01-IMC-01_001            563
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002          487
IMMUcan_Batch20220609_10089094-SPECT-VAR-TIS-01-IMC-01_001         352
IMMUcan_Batch20210506_10068594-SPECT-VAR-TIS-01-IMC-01_003         340
Name: count, Length: 125, dtype: int64

In [71]:
# df.image.values
# == 
df.sample_id.values

['IMMUcan_batch20191023_10032145-THOR-VAR-TIS-0..., 'IMMUcan_batch20191023_10032145-THOR-VAR-TIS-0..., 'IMMUcan_batch20191023_10032145-THOR-VAR-TIS-0..., 'IMMUcan_batch20191023_10032145-THOR-VAR-TIS-0..., 'IMMUcan_batch20191023_10032145-THOR-VAR-TIS-0..., ..., 'IMMUcan_Batch20220908_S-220729-00002_002', 'IMMUcan_Batch20220908_S-220729-00002_002', 'IMMUcan_Batch20220908_S-220729-00002_002', 'IMMUcan_Batch20220908_S-220729-00002_002', 'IMMUcan_Batch20220908_S-220729-00002_002']
Length: 236791
Categories (125, object): ['10068190-SPECT-VAR-TIS-01-IMC-01_001', 'IMMUcan_2022_WFLOW_10034294-GI-VAR-TIS-UNST-0..., 'IMMUcan_2022_WFLOW_10061074-SPECT-VAR-TIS-01-..., 'IMMUcan_2022_WFLOW_10063152-SPECT-VAR-TIS-01-..., ..., 'IMMUcan_SPECTA_LUNG_S-210607-00002_001', 'IMMUcan_WFLOW_Batch20210304_10043243-GI-VAR-T..., 'IMMUcan_WFLOW_Batch20210304_10067564-SPECT-VA..., 'IMMUcan_batch20191023_10032145-THOR-VAR-TIS-0...]

In [65]:
df.image.value_counts()

image
IMMUcan_Batch20210921_LUNG_10041543-LUNG-VAR-TIS-01-IMC-01_003.tiff    5152
IMMUcan_Batch20210921_UPSTREAM_S-210622-00014_004.tiff                 3746
IMMUcan_Batch20210701_UPSTREAM_S-210510-00068_001.tiff                 3488
IMMUcan_Batch20210304_10070084-SPECT-VAR-TIS-01-IMC-01_002.tiff        3439
IMMUcan_Batch20210701_S-210531-00020_001.tiff                          3342
                                                                       ... 
IMMUcan_Batch20201113_10052392-BREAS-VAR-TIS-UNST-03_001.tiff           655
IMMUcan_2022_WFLOW_10072131-SPECT-VAR-TIS-01-IMC-01_001.tiff            563
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff          487
IMMUcan_Batch20220609_10089094-SPECT-VAR-TIS-01-IMC-01_001.tiff         352
IMMUcan_Batch20210506_10068594-SPECT-VAR-TIS-01-IMC-01_003.tiff         340
Name: count, Length: 125, dtype: int64

In [64]:
df.index.value_counts()

IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-IMC-01_002.tiff_1                 1
IMMUcan_SPECTA_LUNG_S-210531-00014_001.tiff_1895                                 1
IMMUcan_SPECTA_LUNG_S-210531-00014_001.tiff_1898                                 1
IMMUcan_SPECTA_LUNG_S-210531-00014_001.tiff_1899                                 1
IMMUcan_SPECTA_LUNG_S-210531-00014_001.tiff_1900                                 1
                                                                                ..
IMMUcan_Batch20210506_UPSTREAM_10064754-E1559-VAR-TIS-01-IMC-01_001.tiff_1049    1
IMMUcan_Batch20210506_UPSTREAM_10064754-E1559-VAR-TIS-01-IMC-01_001.tiff_1050    1
IMMUcan_Batch20210506_UPSTREAM_10064754-E1559-VAR-TIS-01-IMC-01_001.tiff_1051    1
IMMUcan_Batch20210506_UPSTREAM_10064754-E1559-VAR-TIS-01-IMC-01_001.tiff_1052    1
IMMUcan_Batch20220908_S-220729-00002_002.tiff_2725                               1
Name: count, Length: 236791, dtype: int64

In [62]:
df[(df['image'] == df['image'].unique()[0]).values]

image  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
...                                                                                               ...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   

                                                                                            sample_id  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
...                                                                                               ...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01...   

                                                    ObjectNumber       Pos_X  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           1.0  300.846154   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           3.0   26.982143   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           5.0  309.083333   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           7.0  431.916667   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...           8.0  116.931034   
...                                                          ...         ...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...        2702.0  206.957746   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...        2715.0  517.910256   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...        2716.0  541.909091   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...        2718.0  363.404255   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...        2724.0  331.370370   

                                                         Pos_Y  area  \
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    0.692308  13.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    0.928571  56.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    0.750000  12.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    0.750000  12.0   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...    1.206897  29.0   
...                                                        ...   ...   
IMMUcan_batch20191023_10032145-THOR-VAR-TIS-01-...  596.084507  71.0   
IMMUcan_batch20191023_10032145-THOR-V

In [ ]:
for img_name in df['image'].unique():
    df[df['image'] == img_name][['sample_id', 'area', 'eccentricity', 'cell_labels']]

In [76]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
np.unique(le.fit_transform(df['cell_labels'].values))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [78]:
X = np.ones((10, 2))
np.linalg.norm(X[:, None] - X[None, :], axis=-1).shape

(10, 10)

In [79]:
np.nonzero(np.linalg.norm(X[:, None] - X[None, :], axis=-1) < 1)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
        2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
        6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
        8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))

In [81]:
np.max(df[['Pos_X', 'Pos_Y']].values)

639.1052631578947

In [98]:
pos = df[['Pos_X', 'Pos_Y']].values[:100]

In [99]:
neighbourhood_mask = np.linalg.norm(pos[:, None] - pos[None, :], ord=2, axis=-1) <= 50
sample_edges = np.array(np.where(neighbourhood_mask)).T
sample_edges2 = np.nonzero(neighbourhood_mask)

In [100]:
sample_edges2[0][:10]

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [101]:
sample_edges2[1][:10]

array([ 0,  2, 10, 38,  1, 12, 17, 18, 21, 22], dtype=int64)

In [102]:
sample_edges.shape

(908, 2)

In [106]:
np.array(np.where(neighbourhood_mask)).T

array([[ 0,  0],
       [ 0,  2],
       [ 0, 10],
       ...,
       [99, 88],
       [99, 94],
       [99, 99]], dtype=int64)